application: dylanmadisetti
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: static/images
- url: /styles
  static_dir: static/styles
- url: /scripts
  static_dir: static/scripts
- url: /shader
  static_dir: static/shader
- url: /google91792fe8808f769d.html
  static_files: static/google91792fe8808f769d.html
  upload: static/google91792fe8808f769d.html
- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /BingSiteAuth.xml
  static_files: static/BingSiteAuth.xml
  upload: static/BingSiteAuth.xml
- url: /.*
  script: main.app

skip_files:
- google_appengine
- \..*
- README.md
- test*

libraries:
- name: jinja2
  version: latest