application: dylanmadisetti
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images
- url: /stylesheets
  static_dir: stylesheets
- url: /scripts
  static_dir: scripts
- url: /google91792fe8808f769d.html
  static_files: google91792fe8808f769d.html
  upload: google91792fe8808f769d.html
- url: /sitemap.xml
  static_files: sitemap.xml
  upload: sitemap.xml
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /BingSiteAuth.xml
  static_files: BingSiteAuth.xml
  upload: BingSiteAuth.xml
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest